spring:
  application:
    name: orbital-demo
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:${DB_VENDOR:postgresql}://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:orbital_demo}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate

  security:
    oauth2:
      authorization-server:
        client:
          orbital:
            registration:
              client-id: ${CLIENT_ID:orbital}
              client-secret: ${CLIENT_SECRET:$2a$04$Dd7TRyVlyYp9OS0wNOLpFu7cm9oz4xRSKhZkY6Ui0cPbKCqnCksJS}
              client-authentication-methods:
                - client_secret_post
              authorization-grant-types:
                - authorization_code
                - refresh_token
              redirect-uris:
                - http://localhost:${SERVER_PORT:8080}/swagger-ui/oauth2-redirect.html
            token:
              access-token-time-to-live: 1h
              refresh-token-time-to-live: 2h

server:
  port: ${SERVER_PORT:8080}

application:
  constants:
    team-generation:
      budget: 3000000
    players-generation:
      goalkeepers: 3
      defenders: 5
      midfielders: 6
      attackers: 6
      min-age: 18
      max-age: 35
      market-value: 500000